### ISSUE TITLE
City detect not work propetly

### ISSUE THREAD

**Issue by salivo** [Plajta/PlzenskyPoharPravdy#7]
`Exception in thread Thread-702 (_handle_event_internal):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/andry/Hackathon/PlzenskyPoharPravdy/env/lib/python3.11/site-packages/socketio/server.py", line 586, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andry/Hackathon/PlzenskyPoharPravdy/env/lib/python3.11/site-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
           ^^^^^^^^^^^^^^
  File "/home/andry/Hackathon/PlzenskyPoharPravdy/env/lib/python3.11/site-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andry/Hackathon/PlzenskyPoharPravdy/env/lib/python3.11/site-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
          ^^^^^^^^^^^^^^
  File "/home/andry/Hackathon/PlzenskyPoharPravdy/src/main.py", line 107, in handle_nukede
    data_all = int(data_loader.query(f"uzemi_txt=='{city}' and vek_txt.isnull() and pohlavi_txt.isnull()", ["hodnota"])[0][0])
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`


i think its chyba

**Comment by HelloWorld7894** [comment]
Měl jsi správně vygenerované soubory přes fetch.py? Myslím že tohle bude chyba o tom že to ten query nedohledá, každopádně by to chtělo udělat alespoň nějakej try catch s error messagí ať navyskočí takhle hnusnej error

**Comment by HelloWorld7894** [comment]
Hodil jsem do všech generatů a fetchů try/except + hlášku tý chyby, myslím že by do budoucna bylo fajn udělat server logging co by se třeba ukládal do jednoho souboru, aby byly errory/warningy/logy pohromadě
